# WARNING - Generated by {fusen} from dev/flat_fct_add_rprofile_template.Rmd: do not edit by hand

test_that("fct_add_rprofile_template works", {
  expect_output(fct_add_rprofile_template(), "The content has been copied to the clipboard. Please paste it into your .Rprofile file.")
})
