# WARNING - Generated by {fusen} from dev/flat_fct_add_rprofile_template.Rmd: do not edit by hand

test_that("fct_add_rprofile_template validates template file exists", {
  skip_if_not_installed("mockery")

  # Mock system.file to return empty string (simulating missing template)
  mockery::stub(
    fct_add_rprofile_template,
    "system.file",
    ""
  )

  expect_error(
    fct_add_rprofile_template("user"),
    "Could not find R profile template"
  )
})

test_that("fct_add_rprofile_template validates scope parameter", {
  # Invalid scope should fail with match.arg error
  expect_error(
    fct_add_rprofile_template("invalid"),
    "'arg' should be one of"
  )
})

test_that("fct_add_rprofile_template handles missing template file gracefully", {
  skip_if_not_installed("mockery")

  # Mock system.file to return a path that doesn't exist
  mockery::stub(
    fct_add_rprofile_template,
    "system.file",
    "/nonexistent/path/template.R"
  )

  expect_error(
    fct_add_rprofile_template("user"),
    "Could not find R profile template"
  )
})
