# WARNING - Generated by {fusen} from dev/flat_fct_add_rprofile_template.Rmd: do not edit by hand

test_that("copy_to_clipboard handles file reading errors gracefully", {
  # Test with non-existent file
  expect_error(
    copy_to_clipboard("/path/that/does/not/exist.R"),
    "Failed to read template file"
  )
})

test_that("fct_add_rprofile_template validates template file exists", {
  # Mock system.file to return empty string
  mockery::stub(
    fct_add_rprofile_template,
    "system.file",
    ""
  )

  expect_error(
    fct_add_rprofile_template("user"),
    "Could not find R profile template"
  )
})
