# WARNING - Generated by {fusen} from dev/flat_add_template.Rmd: do not edit by hand

# Create a new project
dummypackage <- tempfile(pattern = "add_template")
dir.create(dummypackage)
pkg_name <- basename(dummypackage)

# Helper function to set the working directory using usethis::with_project
with_project_helper <- function(code) {
  usethis::with_project(dummypackage, code, quiet = TRUE, force = TRUE, setwd = TRUE)
}

# Test for add_template ----
test_that("add_template empty call works", {
  with_project_helper({
    # Test for adding dev_history template
    add_template()
    expect_true(file.exists(file.path(dummypackage, "dev", "dev_history.Rmd")))
  })
})


test_that("add_template adds multiple templates sequentially", {
  with_project_helper({
    # Add multiple templates
    add_template(template = "dev_history.Rmd", save_as = "dev_history2.Rmd")
    expect_true(file.exists(file.path(dummypackage, "dev", "dev_history.Rmd")))

    add_template(template = "flat_fct_load_data.Rmd", save_as = "fct_load_data.Rmd")
    expect_true(file.exists(file.path(dummypackage, "dev", "fct_load_data.Rmd")))
  })
})


test_that("add_template saves templates with custom file names", {
  with_project_helper({
    # Add template with custom save_as name
    add_template(template = "dev_history.Rmd", save_as = "custom_dev_history.Rmd")
    expect_true(file.exists(file.path(dummypackage, "dev", "custom_dev_history.Rmd")))
  })
})

test_that("add_template _targets.R works", {
  with_project_helper({
    # Add template with custom save_as name
    add_template(template = "_targets.R", save_as = "bla.R")
    expect_true(file.exists(file.path(dummypackage, "bla.R")))
  })
})

test_that("add_template argument matching works", {
  with_project_helper({
    add_template(template = "_tar", save_as = "1.R")
    expect_true(file.exists(file.path(dummypackage, "1.R")))
  })
})

test_that("add_template rejects path traversal attempts", {
  with_project_helper({
    # Should reject paths with directory separators
    expect_error(
      add_template(template = "dev_history.Rmd", save_as = "../etc/passwd"),
      "contains directory separators"
    )
    expect_error(
      add_template(template = "dev_history.Rmd", save_as = "../../bad.Rmd"),
      "contains directory separators"
    )
    expect_error(
      add_template(template = "dev_history.Rmd", save_as = "subdir/file.Rmd"),
      "contains directory separators"
    )
  })
})

test_that("add_template rejects empty filenames", {
  with_project_helper({
    expect_error(
      add_template(template = "dev_history.Rmd", save_as = ""),
      "must be a valid file name"
    )
    expect_error(
      add_template(template = "dev_history.Rmd", save_as = "   "),
      "must be a valid file name"
    )
  })
})

test_that("add_template respects overwrite parameter", {
  with_project_helper({
    # Create a file
    add_template(template = "dev_history.Rmd")

    # Should fail without overwrite
    expect_error(
      add_template(template = "dev_history.Rmd"),
      "already exists"
    )

    # Should succeed with overwrite
    expect_no_error(
      add_template(template = "dev_history.Rmd", overwrite = TRUE)
    )
  })
})

unlink(dummypackage, recursive = TRUE)
