# WARNING - Generated by {fusen} from dev/flat_add_template.Rmd: do not edit by hand

# Create a new project
dummypackage <- tempfile(pattern = "add.template")
dir.create(dummypackage)
pkg_name <- basename(dummypackage)

# add_template ----
test_that("add_template adds template", {
  add_template(pkg = dummypackage)
  expect_true(file.exists(file.path(dummypackage, "dev", "0-dev_history.Rmd")))
  expect_true(file.exists(file.path(dummypackage, ".here")))

  rbuildignore_file <- file.path(dummypackage, ".Rbuildignore")
  expect_true(file.exists(rbuildignore_file))
  rbuildignore_lines <- readLines(rbuildignore_file)
  expect_true(any(grepl("^dev$", rbuildignore_lines, fixed = TRUE)))
  expect_true(any(grepl("[.]here", rbuildignore_lines)))

  gitignore_file <- file.path(dummypackage, "dev", ".gitignore")
  expect_true(file.exists(gitignore_file))
  gitignore_lines <- readLines(gitignore_file)
  expect_equal(object = gitignore_lines, expected = "*.html")

  # Second time message and new file
  expect_message(add_template(pkg = dummypackage))
})
unlink(dummypackage, recursive = TRUE)

# local_file_ignore works ----
test_that("local_file_ignore works", {
  tmpdirectory <- tempfile()
  dir.create(tmpdirectory)

  anyfile <- file.path(tmpdirectory, "whatever")
  local_file_ignore(file = anyfile, ignores = c("whatever", "^.other/$"))
  lines <- readLines(anyfile)
  expect_equal(
    object = lines,
    expected = c("whatever", "^.other/$")
  )

  # Add over
  local_file_ignore(file = anyfile, ignores = c("whatever", "something.else"))
  lines <- readLines(anyfile)
  expect_equal(
    object = lines,
    expected = c("whatever", "^.other/$", "something.else")
  )

  # Clean
  unlink(tmpdirectory)
})
