# WARNING - Generated by {fusen} from dev/flat_add_template.Rmd: do not edit by hand

#' Add Rmd template
#'
#' @param template Name of the template to use. See details.
#' @param pkg Path where to save file
#' @param overwrite Whether to overwrite existing Rmd template file with same name
#' @param open Logical. Whether to open file after creation
#' @param dev_dir Name of directory for development Rmarkdown files. Default to "dev".
#' @param template_name Name of the file to write in dev.
#'
#' @details
#' This function was adapted from the awesome `{fusen}` package.
#'
#' Choose `template` among the different templates available:
#'
#' - "dev_history": Template with functions commonly used during package development.
#' - "load_data": `{fusen}`flat file for a data loading function template.
#'
#' @rdname add_template
#' @return
#' Create Rmd file(s) template(s) and return its (their) path
#' @export
#'
#' @examples
#' # For classical use in your package
#' \dontrun{
#' # add only the dev_history file in an existing package
#' add_template()
#' }
#'
#' # For classical use in your package
#' \dontrun{
#' # add only the dev_history file in an existing package
#' add_template()
#' }
add_template <- function(
    template = c(
      "dev_history.Rmd", "fct_load_data.Rmd", "fct_clean_data.Rmd",
      "exploratory_data_analysis.qmd",
      "model_workflow_for_inference.qmd"
    ),
    pkg = ".",
    save_as = template,
    open = TRUE) {
  tryCatch(
    expr = {
      # browser()
      # Check if the file already exists
      pkg <- normalizePath(pkg)
      full_dev_dir <- file.path(pkg, "dev")

      file_path <- file.path(full_dev_dir, save_as[1])
      if (file.exists(file_path)) {
        stop(sprintf("The file %s already exists. Please choose a different
                     name or delete the existing file.", file_path))
      }

      if (!dir.exists(full_dev_dir)) {
        dir.create(full_dev_dir)
      }

      use_template(
        template = template[1],
        save_as = paste0("dev/", template[1]),
        # data = list(), # Use to autofill fields?
        open = open,
        package = "setupR"
      )
    },
    error = function(e) {
      print(
        sprintf(
          "An error occurred in add_template at %s : %s", Sys.time(),
          e
        )
      )
    }
  )
}

#' Retrieve name of the package if there is a DESCRIPTION
#' @noRd
get_pkg_name <- function(pkg) {
  desc <- file.path(pkg, "DESCRIPTION")
  if (file.exists(desc)) {
    pkgname <- read.dcf(desc)[colnames(read.dcf(desc)) == "Package"]
  } else {
    pkgname <- basename(normalizePath(pkg, mustWork = FALSE))
  }
  pkgname
}
