# WARNING - Generated by {fusen} from dev/flat_add_template.Rmd: do not edit by hand

template_choices <- c(
  "dev_history",
  "dev"
)


#' Add Rmd template
#'
#' @param template Name of the template to use. See details.
#' @param pkg Path where to save file
#' @param overwrite Whether to overwrite existing Rmd template file with same name
#' @param open Logical. Whether to open file after creation
#' @param dev_dir Name of directory for development Rmarkdown files. Default to "dev".
#' @param template_name Name of the file to write in dev.
#'
#' @details
#' This function was adapted from the awesome `{fusen}` package.
#'
#' Choose `template` among the different templates available:
#'
#' - "dev_history": Template with functions commonly used during package development.
#'
#' @rdname add_template
#' @return
#' Create Rmd file(s) template(s) and return its (their) path
#' @export
#'
#' @examples
#' # For classical use in your package
#' \dontrun{
#' # add only the dev_history file in an existing package
#' add_template()
#' }
add_template <- function(
    template = c("dev_history"),
    pkg = ".",
    dev_dir = "dev",
    template_name = NULL,
    overwrite = FALSE,
    open = TRUE) {
  project_name <- fusen:::get_pkg_name(pkg = pkg)

  if (project_name != fusen:::asciify_name(project_name, to_pkg = TRUE)) {
    stop(
      "Please rename your project/directory with: `",
      fusen:::asciify_name(project_name, to_pkg = TRUE),
      "` as a package name should only contain letters, numbers and dots."
    )
  }

  template <- template[1]
  template <- match.arg(template, choices = template_choices)

  if (is.null(template_name)) {
    template_name <- template
  }

  if (template == "dev_history") {
    dev_file_path <- character(0)
  }

  pkg <- normalizePath(pkg)
  full_dev_dir <- file.path(pkg, dev_dir)
  if (!dir.exists(full_dev_dir)) {
    dir.create(full_dev_dir)
  }
  dev_file_path <- file.path(full_dev_dir, template_name) # "dev_history.Rmd")

  # Add the-dev-history when needed ----
  if (template %in% c("dev_history")) {
    dev_file <- file.path(full_dev_dir, "0-dev_history.Rmd")
    if (file.exists(dev_file) & !isTRUE(overwrite)) {
      message(
        "'0-dev_history.Rmd' already exists. It was not overwritten. ",
        "Set `add_template(overwrite = TRUE)` if you want to do so."
      )
    } else {
      copy <- file.copy(
        system.file("dev_history.Rmd", package = "setupR"),
        dev_file,
        overwrite = overwrite
      )
      if (!copy) {
        stop("'0-dev_history.Rmd' could not be created in '", full_dev_dir, "'")
      }
      dev_file_path <- c(dev_file_path, dev_file)
    }
  }

  # .Rbuildignore ----
  # usethis::use_build_ignore(dev_dir) # Cannot be used outside project
  if (length(list.files(pkg, pattern = "[.]Rproj")) == 0) {
    ignores <- c(paste0("^", dev_dir, "$"), "^\\.here$")
  } else {
    ignores <- c(paste0("^", dev_dir, "$"))
  }

  local_file_ignore(file = file.path(pkg, ".Rbuildignore"), ignores)

  # Add a gitignore file in dev_dir ----
  # Files to ignore
  ignores <- c("*.html")
  local_file_ignore(file = file.path(full_dev_dir, ".gitignore"), ignores)

  if (length(list.files(pkg, pattern = "[.]Rproj")) == 0 &
    !any(grepl("^[.]here$", list.files(pkg, all.files = TRUE)))) {
    here::set_here(pkg)
  }
  if (isTRUE(open) & interactive()) {
    lapply(dev_file_path, usethis::edit_file)
  }
  dev_file_path
}

#' Add new lines in a file if they are different from what exists
#' @noRd
local_file_ignore <- function(file, ignores) {
  buildfile <- normalizePath(file, mustWork = FALSE)
  if (!file.exists(buildfile)) {
    existing_lines <- character(0)
  } else {
    existing_lines <- readLines(buildfile, warn = FALSE, encoding = "UTF-8")
  }
  new <- setdiff(ignores, existing_lines)
  if (length(new) != 0) {
    all <- c(existing_lines, new)
    cat(enc2utf8(all), file = buildfile, sep = "\n")
  }
}
