# WARNING - Generated by {fusen} from dev/flat_fct_add_rprofile_template.Rmd: do not edit by hand

#' Add R profile template
#'
#' Adds best-practice R profile configuration to your R profile file. The template
#' includes settings for automatic package installation, description defaults,
#' partial match warnings, and autocompletion. The content is copied to your
#' clipboard and the R profile file is opened for editing.
#'
#' @param scope Character. Scope of the .Rprofile file to edit. One of:
#' * `"user"` - Edit user-level .Rprofile (applies to all R sessions)
#' * `"project"` - Edit project-level .Rprofile (applies only to current project)
#' @return Invisibly returns TRUE if successful, FALSE if clipboard unavailable.
#' @seealso
#'  \code{\link[usethis]{edit}}
#' @export
#' @examples
#' \dontrun{
#' # Add template to user R profile
#' fct_add_rprofile_template("user")
#'
#' # Add template to project R profile
#' fct_add_rprofile_template("project")
#' }
fct_add_rprofile_template <- function(scope = c("user", "project")) {
  scope <- match.arg(scope)

  template <- system.file("templates", "rprofile_template.R", package = "setupR")

  if (template == "" || !file.exists(template)) {
    cli::cli_abort(c(
      "x" = "Could not find R profile template.",
      "i" = "Please ensure the setupR package is properly installed."
    ))
  }

  clipboard_success <- copy_to_clipboard(template)

  if (clipboard_success) {
    cli::cli_alert_info("The content has been copied to the clipboard. Please paste it into your .Rprofile file.")
  } else {
    cli::cli_alert_warning("Clipboard not available. Please copy the content manually from the opened file.")
  }

  cli::cli_alert_info("Opening .Rprofile file for editing...")

  usethis::edit_r_profile(scope)

  invisible(clipboard_success)
}

#' @noRd
copy_to_clipboard <- function(template) {
  # Read template file with error handling
  content <- tryCatch(
    readLines(template, warn = FALSE),
    error = function(e) {
      cli::cli_abort(c(
        "x" = "Failed to read template file.",
        "i" = "Error: {e$message}"
      ))
    }
  )

  if (clipr::clipr_available()) {
    tryCatch(
      {
        x <- crayon::strip_style(content)
        clipr::write_clip(x)
        cli::cli_alert_success("Content copied to clipboard")
        return(TRUE)
      },
      error = function(e) {
        cli::cli_alert_warning("Failed to copy to clipboard: {e$message}")
        return(FALSE)
      }
    )
  } else {
    return(FALSE)
  }
}
