# WARNING - Generated by {fusen} from dev/flat_fct_add_rprofile_template.Rmd: do not edit by hand

#' @title Add Rprofile template
#'
#' @param scope Scope of the .Rprofile file to edit.
#' @return .rprofile template content copied to clipboard.
#' @seealso
#'  \code{\link[usethis]{edit}}
#' @export
#' @examples
#' if (FALSE) {
#'   fct_add_rprofile_template()
#' }
fct_add_rprofile_template <- function(scope = c("user", "project")) {
  template <- system.file("templates", "rprofile_template.R", package = "setupR")

  copy_to_clipboard(template)

  cat("The content has been copied to the clipboard. Please paste it into your .Rprofile file.\n")

  open_rprofile <- readline(prompt = "Do you want to open the .Rprofile file? (yes/no) ")

  if (open_rprofile == "yes") {
    usethis::edit_r_profile(scope)
  } else {
    cat("Aborted.\n")
  }
}

#' @noRd
copy_to_clipboard <- function(template) {
  content <- readLines(template)
  utils::writeClipboard(content)
}
